---
- name: Blacklist drivers
  ansible.builtin.lineinfile:
    path: "{{ proxmox_driver_blacklist_file_path }}"
    line: "blacklist {{ item }}"
    mode: "{{ proxmox_driver_blacklist_file_mode }}"
    create: true
  loop: "{{ proxmox_driver_blacklist }}"
  notify:
    - Update initramfs
    - Reboot
